### ISSUE TITLE
Tunnel

### ISSUE THREAD

**Issue by mmddks** [ShadowsocksR-Live/shadowsocksr#2]
Hello, in Iran, the internet is often internal, I have tried many tunnels to connect two servers for this protocol, but I have not succeeded in connecting with the tunnel, what tunnel should I run?

**Comment by ssrlive** [comment]
Hi here, since SSR can not work fine for you, you can have a taste to my new toy [overtls](https://github.com/ssrlive/overtls) that can pass China GFW smoothly.
